// <auto-generated />
namespace MedicalDocManagment.UsersDAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class Fix_wrong_relationship_between_user_and_position : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Fix_wrong_relationship_between_user_and_position));
        
        string IMigrationMetadata.Id
        {
            get { return "201703261548249_Fix_wrong_relationship_between_user_and_position"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
