// <auto-generated />
namespace MedicalDocManagment.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class Featurefill_form_psychiatrist : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Featurefill_form_psychiatrist));
        
        string IMigrationMetadata.Id
        {
            get { return "201704281351040_Feature-fill_form_psychiatrist"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
