// <auto-generated />
namespace MedicalDocManagment.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class Improvementcomponent_for_adding_parent_to_user_card : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Improvementcomponent_for_adding_parent_to_user_card));
        
        string IMigrationMetadata.Id
        {
            get { return "201705151252104_Improvement-component_for_adding_parent_to_user_card"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
