// <auto-generated />
namespace MedicalDocManagment.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class FeatureFill_form_pediatrician : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(FeatureFill_form_pediatrician));
        
        string IMigrationMetadata.Id
        {
            get { return "201705071936271_Feature-Fill_form_pediatrician"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
