// <auto-generated />
namespace MedicalDocManagment.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class FeatureForm_neurologist : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(FeatureForm_neurologist));
        
        string IMigrationMetadata.Id
        {
            get { return "201706131238445_Feature-Form_neurologist"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
