// <auto-generated />
namespace MedicalDocManagment.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class Fill_form_neurologist1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Fill_form_neurologist1));
        
        string IMigrationMetadata.Id
        {
            get { return "201705300854274_Fill_form_neurologist1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
