// <auto-generated />
namespace MedicalDocManagment.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class Feature_form_speech_therapist : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Feature_form_speech_therapist));
        
        string IMigrationMetadata.Id
        {
            get { return "201706081459400_Feature_form_speech_therapist"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
